### ISSUE TITLE
.NET Core 1.1.4 0x80070003 the system cannot find the path specified

### ISSUE THREAD

**Issue by sballarati** [aspnet/IISIntegration#474] opened 2017-11-14 22:12 UTC
Microsoft .NET Core 1.0.7 & 1.1.4
Windows Server 2008 R2 SP1  
Burn v3.10.3.3007, Windows v6.1 (Build 7601: Service Pack 1)

Visual C++ 2015 installed. Unfortunately this solution from #179 did not work for me.

Attaching the log:

[dd_DotNetCoreWinSvrHosting__20171114215006.log](https://github.com/aspnet/IISIntegration/files/1472702/dd_DotNetCoreWinSvrHosting__20171114215006.log)

Thoughts? Anything else I can try to get .NET Core working?

Thanks in advance!

Sebastian

**Comment by Tratcher** [comment] 2017-11-14 22:14
@joeloff

**Comment by joeloff** [comment] 2017-11-14 23:08
@sballarati do you have the installation log from the .NET Core runtime? It will be in your %temp% folder and be named something like Microsoft_.NET_Core_1.0.7_-_Runtime_(x64)_nnnnnn.log

**Comment by sballarati** [comment] 2017-11-29 20:05
[Microsoft_.NET_Core_1.0.7_-_Runtime_(x64)_20171114215721.log](https://github.com/aspnet/IISIntegration/files/1515352/Microsoft_.NET_Core_1.0.7_-_Runtime_.x64._20171114215721.log)

@joeloff thanks for looking into it.

**Comment by joeloff** [comment] 2017-11-29 20:53
Looks like it's not able to access the URL for downloading the VC redist. Do you have internet access from the machine? I've seen instances where servers on which the hosting bundle was installed could not access outside items.

In .NET Core 1.0 runtime, it still depends on the C++ redists and those are downloaded dynamically, which I know defeats the purpose of having a selfcontained bundle that still needs to go online.

From the logs you sent:
[20C0:0858][2017-11-14T21:57:48]e000: Error 0x80072f19: Failed to send request to URL: **https://download.microsoft.com/download/1/F/0/1F01DD22-748C-41A7-89DE-54D64355CDA6/vc_redist.x64.exe**, trying to process HTTP status code anyway.

One option would be to simply download the VC redist, copy it to the machine, install it first and then install the hosting bundle.

In 2.0 this has been addressed and the C++ redist dependency has been removed.

**Comment by sballarati** [comment] 2017-11-29 21:41
Thanks for your help! Actually, the VC redist was installed before running the bundle, I found this file in the temp folder too:

[dd_vcredist_amd64_20171114220611.log](https://github.com/aspnet/IISIntegration/files/1515630/dd_vcredist_amd64_20171114220611.log)

**Comment by joeloff** [comment] 2017-11-29 22:07
Ah, so the catch is that with bundles, even if they fail to install they will still create an entry in ARP. They will also fail to install anything else after the initial failure. If the runtime was installed there should also be an entry in ARP for the 1.0.7 and the 1.1.4 runtimes themselves? Do you see those?

**Comment by shirhatti** [comment] 2018-02-26 23:01
Hi. We're closing this issue as no response or updates have been provided   in a timely manner and we have been unable to reproduce it. If you have more   details and are encountering this issue please add a new reply and re-open   the issue.

**Closed** 2018-03-05 23:42 UTC
