### ISSUE TITLE
Request Stream is not always correct in inprocess mode in 2.1.0-preview1-final

### ISSUE THREAD

**Issue by Tornhoof** [aspnet/IISIntegration#728] opened 2018-03-26 14:22 UTC
I noticed during my load tests, that my batch middleware sometimes returned 500, after a few hours of trying to reproduce it, I think that the Request Streams sometimes is missing data in the middle of the stream (maybe at the boundary of a buffer?)

Steps to reproduce:
[BadRequestStream.zip](https://github.com/aspnet/IISIntegration/files/1848129/BadRequestStream.zip)
1. Run the App from the zip above in inprocess mode (in my case IIS 10 in Windows 10, B1709)
2. Create a postman request and add the information from Request.txt and run it (e.g. click send until a 400 Bad Request error is shown with the error below).
3. if the error occurs you see the following result
``ion/json;domain-model=CreateMPPhPCommand Host: localhost Content-ID: 24 {}``
you can e.g. disable the Authorization header, then the error is a different text string
``nt-Type: application/json;domain-model=LinkIngredientToManufacturedItemCommand If-Match: "*" Host: localhost {"LinkAggregateId":"$49"}``

Information:
The request is a multipart request, most of the times the parsed multipart section is somehow too long and reads into the next multipart section. Apparently it's dependent on the request length, because the difference between both error messages in the request body is exactly the length of the Authorization header (12243).

Note: the same error does not appear in outprocess mode, so I think it's a bug in the Microsoft.AspNetCore.Server.IISIntegration.IISHttpRequestBody.
On my system the first request is successful, all other following requests are bad, maybe bad buffer pool?

**Comment by Tornhoof** [comment] 2018-03-26 19:08
I had to change the port and ``result.EnsureSuccessStatusCode();`` does not show the exception
if I change it to
```csharp
if (result.StatusCode != HttpStatusCode.OK)
{
    var output = await result.Content.ReadAsStringAsync();
    Console.WriteLine("Error: {0}", output);
}
```
It shows the error immediately. With a slightly different error text, probably because Postman adds additional tracking headers.

**Comment by pakrym** [comment] 2018-03-27 15:55
@Tornhoof can you please try https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1 build.

We had a large refactoring in related area post preview1 and my tests show that issue doesn't reproduce in later builds.

**Comment by Tornhoof** [comment] 2018-03-27 17:10
Ok, I think it's fixed, I'll try tomorrow with the full application, this is just my repro, just for reference what I did:
- Install the SDK and ASP.NET Runtimes from https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1
- Changed to .\install-ancm.ps1 to use the myget feed (the changed ps1 (renamed txt) is attached)
- Edited the PackageReferences in my project to use 2.1.0-preview2-30457 for AspNetCore
- dotnet publish
- Replaced the files and ran it

Result: I can run it as much as I like, no errors yet.
[install-ancm.txt](https://github.com/aspnet/IISIntegration/files/1853001/install-ancm.txt)

I'll report back tomorrow with the full application.

**Comment by Tornhoof** [comment] 2018-03-28 08:53
I'm sorry, I can't test the full application, as it does not work anymore with the recent build version, it dies on startup at with the following exception:
```csharp
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
  Source=System.Private.CoreLib
  StackTrace:
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.RelatedAssemblyAttribute.GetRelatedAssemblies(Assembly assembly, Boolean throwOnError, Func`2 fileExists, Func`2 loadFile) in D:\b\w\33bdfc1cae7b2a38\modules\Mvc\src\Microsoft.AspNetCore.Mvc.Core\ApplicationParts\RelatedAssemblyAttribute.cs:line 95
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationAssembliesProvider.GetAssemblyItem(Assembly assembly) in D:\b\w\33bdfc1cae7b2a38\modules\Mvc\src\Microsoft.AspNetCore.Mvc.Core\ApplicationParts\ApplicationAssembliesProvider.cs:line 129
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationAssembliesProvider.ResolveFromDependencyContext(DependencyContext dependencyContext) in D:\b\w\33bdfc1cae7b2a38\modules\Mvc\src\Microsoft.AspNetCore.Mvc.Core\ApplicationParts\ApplicationAssembliesProvider.cs:line 87
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationAssembliesProvider.<ResolveAssemblies>d__3.MoveNext() in D:\b\w\33bdfc1cae7b2a38\modules\Mvc\src\Microsoft.AspNetCore.Mvc.Core\ApplicationParts\ApplicationAssembliesProvider.cs:line 56
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateDefaultParts(String entryAssemblyName) in D:\b\w\33bdfc1cae7b2a38\modules\Mvc\src\Microsoft.AspNetCore.Mvc.Core\ApplicationParts\ApplicationPartManager.cs:line 59
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services) in D:\b\w\33bdfc1cae7b2a38\modules\Mvc\src\Microsoft.AspNetCore.Mvc.Core\DependencyInjection\MvcCoreServiceCollectionExtensions.cs:line 93
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services) in D:\b\w\33bdfc1cae7b2a38\modules\Mvc\src\Microsoft.AspNetCore.Mvc.Core\DependencyInjection\MvcCoreServiceCollectionExtensions.cs:line 51
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services, Action`1 setupAction) in D:\b\w\33bdfc1cae7b2a38\modules\Mvc\src\Microsoft.AspNetCore.Mvc.Core\DependencyInjection\MvcCoreServiceCollectionExtensions.cs:line 129
```
I don't yet know what that error is.

**Comment by Tornhoof** [comment] 2018-03-28 09:11
Looks like it fails because of #725 
The Uri Parser can't handle that extended length filename stuff
Repro:
```csharp
var path = "file:////?/C:/InProcess/MyApp.WebAPI.dll";
if (Uri.TryCreate(path, UriKind.Absolute, out var result) && result.IsFile)
{
    var localPath = result.LocalPath;
    Console.WriteLine(localPath);
    var directoryName = Path.GetDirectoryName(localPath);                
    Console.WriteLine(directoryName);
    if(directoryName == null)
    {
        Console.WriteLine("It's null.");
    }
}
```

**Comment by pakrym** [comment] 2018-03-28 23:55
I'm closing this because request corruption seems to be addressed, we are tracking path issue and workaround separately.

**Closed by pakrym** 2018-03-28 23:55 UTC
Labels: 2 - Working, bug, cost: M

**Comment by Tornhoof** [comment] 2018-03-29 10:40
I can confirm that the error is gone with the latest ANCM (2.1.0-preview2-30500) and a fairly recent sdk (yesterday or the day before). I can run my load test without any of the errors above.

I can't say for performance differences specifically for the inprocess/outprocess mode, because the sdk was quite different too, anyway (both on the same Azure Environment, same JMeter test script):

- NetFX 4.7 with ASP.NET Core 2.0: 2685 req/s
- NET Core 2.1: Out of Process with 2.1.0-preview1-final: 2856 req/s
- NET Core 2.1: InProcess with 2.1.0-preview2-30457 (or similar):  3390 req/s

Main difference I saw was that the response time 99% percentile was ~40% better in the inprocess version. As usual take those values with a grain of salt ;)

My previous install script for ancm apparently used the wrong myget url, here is a corrected one.
[install-ancm.txt](https://github.com/aspnet/IISIntegration/files/1859669/install-ancm.txt)
