### ISSUE TITLE
ShutDown anything without Ctrl-C

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#906] opened 2018-06-11 15:15 UTC
_From @ziyaozclk on June 11, 2018 8:31_

StopAsync is not triggered when I close an application that is running on IIS. Only when triggered key press Ctrl-C. Help me :)

_Copied from original issue: aspnet/Hosting#1455_

**Comment by Tratcher** [comment] 2018-06-11 15:15
How do you close an application running on IIS?

**Comment by jkotalik** [comment] 2018-06-11 15:29
Also, how are you inputting Ctrl-C to IIS? Are you running IIS with a console? IISExpress?

Here is a doc about shutting down an IIS app pool with a powershell script.

**Comment by muratg** [comment] 2018-06-11 18:04
@ziyaozclk I assume you're not using IIS for the case where you stop the app with Ctrl-C and see StopAsync being triggered. Let me know if this is not correct.

cc @pan-wang

**Comment by ziyaozclk** [comment] 2018-06-11 18:41
@Tratcher I choose the site I want to close on IIS. I use the stop button from the Actions menu on the right

**Comment by ziyaozclk** [comment] 2018-06-11 18:42
@jkotalik @muratg  When I closed it with Ctrl-C, it run as Console Application in Visual Studio. When run like this, it triggers into the StopAsyn method.

**Comment by pan-wang** [comment] 2018-06-11 20:08
@ziyaozclk  this is by design for ANCM V1. In V1, ANCM is just an IIS pipeline module and never listen on worker process recycle notification. In case of worker process recycle, the module context was cleaned too later and ANCM had no chance to notify the backend. This has been fixed in V2 code and will be released with in process support.

**Comment by aspnet-hello** [comment] 2018-09-24 18:11
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.

**Closed by aspnet-hello** 2018-09-24 18:12 UTC
