### ISSUE TITLE
403 Error debugging Core 2.1 MVC with IIE Express

### ISSUE THREAD

**Issue by jastralfu** [aspnet/IISIntegration#1315] opened 2018-08-23 15:38 UTC
I think this is a bug but am not entirely sure. I have created an ASP.NET Core 2.1 MVC Web app with the default template. I have changed nothing with the default application save for updating the IIS Express applicationhost.config to enable SSL by changing the access sslFlags to sslFlags="Ssl, SslNegotiateCert, SslRequireCert". When I debug from Visual Studio 2017 I get the following error:
Unable to start process C:\Program Files\dotnet\dotnet.exe. The web server request failed with status code 403, Forbidden.
From the HttpFailure and the IIS Express TraceLogFile files it seems as though IIS Express is trying to open the http url rather than the https url. The launchsettings.json has an SSL port defined but it is not using it.
If I run the application without debugging (ctrl + f5) the site opens using the https url and prompts for a client certificate. Is this a bug or am I missing something?

To reproduce this

create a new ASP.NET Core 2.1 Web MVC Applicationproject enabling https with no authentication.
Update the applicationhost.config file in the .vs/config folder of the project and replace access sslFlags="None" with access sslFlags="Ssl, SslNegotiateCert, SslRequireCert".
Debug with IIS Express (f5).

**Comment by shirhatti** [comment] 2018-08-24 18:42
@BillHiebert

**Comment by shirhatti** [comment] 2018-08-24 18:46
If I'm not mistaken, this is a known limitation with ClientCert authentication (or Windows Authentication). Bill can confirm

**Comment by BillHiebert** [comment] 2018-08-24 18:54
Correct. Please see https://github.com/aspnet/Mvc/issues/8314, and https://github.com/aspnet/SignalR/issues/2259

**Comment by shirhatti** [comment] 2018-08-24 18:57
Closing as duplicate of known issue.

**Closed by shirhatti** 2018-08-24 18:57 UTC
