### ISSUE TITLE
Publish tool does not account for outputName in project.json

### ISSUE THREAD

**Issue by pranavkm** [aspnet/IISIntegration#163] opened 2016-05-05 01:16 UTC
```
/Test/project.json
{
   "buildOptions": { "outputName": "DifferentName" }
   ...
}
```

produces a web.config
```
 <aspNetCore processPath="dotnet" arguments=".\Test.dll"
```

Similar issue with standalone applications.

**Comment by moozzyk** [comment] 2016-05-05 01:21
Dupe of https://github.com/aspnet/IISIntegration/issues/128

**Closed by moozzyk** 2016-05-05 01:21 UTC
