### ISSUE TITLE
User.Identity.Name is null

### ISSUE THREAD

**Issue by danjford** [aspnet/IISIntegration#278] opened 2016-10-04 16:15 UTC
Hi,

When running my application in Visual Studio 2015, I can access my User's Name by using User.Identity.Name.

However, when I publish my application using `dotnet publish -c release` and run the resulting `.exe` from the publish folder, my application loads but `User.Identity.Name` is null which causes issues in parts of the system.

On publish my project has the same config as [aspnet/JavascriptServices](https://github.com/aspnet/JavaScriptServices/tree/dev/templates/Angular2Spa) i.e. 

```
  "scripts": {
    "prepublish": [
      "npm install",
      "node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --env.prod",
      "node node_modules/webpack/bin/webpack.js --env.prod"
    ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },
```

The `windowsAuthentication` and `anonymousAuthentication` properties are configured in `launchSettings.json` i.e. 

```
{
  "iisSettings": {
      "windowsAuthentication": true,
      "anonymousAuthentication": false
   }
}
```

**Comment by Tratcher** [comment] 2016-10-04 17:12
Windows auth requires IIS/Express (or WebListener). When you run the exe directly from the folder it does not run IIS/Express, only Kestrel. Also, launchsettings only apply inside of VS. Run your site in IIS with WindowsAuth enabled.

**Comment by danjford** [comment] 2016-10-04 17:20
Ok, but the user also seems to be null on the `Windows 2008 R2` server where the Authentication settings have been set up to have `Windows Authentication: Enabled` and `Anonymous Authentication: Disabled`

**Comment by Tratcher** [comment] 2016-10-04 17:22
Inside IIS you mean?

**Comment by danjford** [comment] 2016-10-04 17:24
In the IIS Manager, yes.

**Comment by Tratcher** [comment] 2016-10-04 17:29
Make sure `forwardWindowsAuthToken="false"` is enabled in the web.config
https://github.com/aspnet/JavaScriptServices/blob/dev/templates/Angular2Spa/web.config#L12

**Comment by danjford** [comment] 2016-10-04 17:32
This is what my web.config looks like:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <!--
    Configure your application settings in appsettings.json. Learn more at http://go.microsoft.com/fwlink/?LinkId=786380
  -->
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="true" />
  </system.webServer>
</configuration>
```

**Comment by danjford** [comment] 2016-10-05 17:35
Have had a further look and this may have been caused by configurations in another library affecting this, I will investigate further.

**Comment by muratg** [comment] 2017-05-12 21:27
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Closed by muratg** 2017-05-12 21:27 UTC
Labels: invalid

**Comment by DanJ210** [comment] 2018-10-17 22:21
I am having this same exact issue with a .Net Core 2.1 project. When I run it using Visual Studio 2017 it works. The `forwardWindowsAuthToken` flag actually breaks the application and I get a 404 not found page. I can't figure out what the problem is. Windows auth is enabled in IIS and anonymous is disabled.

**Comment by Tratcher** [comment] 2018-10-17 22:30
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.
