### ISSUE TITLE
Microsoft.AspNetCore.Diagnostics FileLoadException (in use) after Azure web app restart

### ISSUE THREAD

**Issue by razzemans** [aspnet/IISIntegration#378] opened 2017-06-06 08:09 UTC
Last night our Azure web app restarted (automatically) and didn't come back online. It failed with an Application Startup Error. Looking at the stdout logs, the only error I could see on one of our two instances was:

```
Application startup exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNetCore.Diagnostics, Version=1.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)
File name: 'Microsoft.AspNetCore.Diagnostics, Version=1.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at OurProductionApp.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass3_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

The eventlog has an entry around the same time:

```
<Event>
        <System>
            <Provider Name="IIS AspNetCore Module"/>
            <EventID>1000</EventID>
            <Level>0</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2017-06-05T20:49:40Z"/>
            <EventRecordID>1452296781</EventRecordID>
            <Channel>Application</Channel>
            <Computer>RD00155D587183</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Application 'MACHINE/WEBROOT/APPHOST/OURWEBAPPLICATION__6E0C' with physical root 'D:\home\site\wwwroot\' failed to start process with commandline '"dotnet" .\OurWebApplication.dll', ErrorCode = '0x80004005 : e0434352.</Data>
        </EventData>
    </Event>
```

On another note, I can see this error quite often in the eventlog, a couple of times in the past few weeks. It might even be related to my other issue (#365) as we've had some of our instances suddenly serving 500 errors. Maybe the underlying trigger was in fact also an Azure restart causing the server to not restart correctly. Note that that is pure speculation, I do not have any metrics yet to support this. The symptoms look a little bit different, but I can't rule it out either.

I will also start an Azure support ticket, but I've never had this issue running our .NET 4.5 projects in production for 3 years.

**Comment by Tratcher** [comment] 2017-09-13 16:30
@Eilon who's the best person to look at this?

**Comment by Eilon** [comment] 2017-09-13 21:08
@Tratcher I emailed you the internal email alias for Antares+ASP.NET Core questions/discussions.

**Comment by Tratcher** [comment] 2017-10-17 22:31
@razzemans you resolved this with your support rep, correct?

**Comment by razzemans** [comment] 2017-10-18 06:34
@Tratcher no, not this issue. I haven't run into this issue again though, so unless you want to take some additional action, go ahead and close this.

**Comment by razzemans** [comment] 2017-10-18 13:18
@Tratcher well you wouldn't believe it, but today I changed a setting in the Azure Portal for our web application, clicked 'Restart', and boom, my application crashed. The stdout log showed:

```
Application startup exception: System.IO.FileLoadException: Could not load file or assembly 'OurCustomLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)
File name: 'OurCustomLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Our.Web.Application.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

So this still happens...

**Comment by Tratcher** [comment] 2017-10-20 16:44
@razzemans was this also fixed by removing AI?
https://github.com/aspnet/IISIntegration/issues/252#issuecomment-337854142

**Comment by razzemans** [comment] 2017-10-23 07:01
@Tratcher no, this is a separate issue. We don't have the AI site extension running on this particular application.

**Comment by muratg** [comment] 2018-02-12 22:50
We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by muratg** 2018-02-12 22:50 UTC
