### ISSUE TITLE
Azure WebApp: Scheme not set to HTTPS, breaks RequireHttps and OAuth/OIDC

### ISSUE THREAD

**Issue by LeandroPT** [aspnet/IISIntegration#140] opened 2016-04-19 01:36 UTC
I have an RC2 Application running on Azure Web App Role.

on the browser side:
https://mydummycisiteci.azurewebsites.net redirected you too many times.

On the stdout log for aspnetcoremodule:
```
info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      Azure Web Sites environment detected. Using 'D:\home\ASP.NET\DataProtection-Keys' as key repository; keys will not be encrypted at rest.
Hosting environment: Production
Content root path: D:\home\site\wwwroot
Now listening on: http://localhost:15934/
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://mydummycisite.azurewebsites.net/  
warn: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.RequireHttpsAttribute'.
info: Microsoft.AspNetCore.Mvc.RedirectResult[1]
      Executing RedirectResult, redirecting to https://mydummycisite.azurewebsites.net/.
```
The most interesting fact is that if if download a resource (image for example)

`info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://mydummycisite.azurewebsites.net/favicon.ico  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1227.537ms 404 `

on the browser side:
`http://mydummycisite.azurewebsites.net/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)`

I have the exact same configuration on Local IIS and works like a candy...

web.config - Azure App
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="D:\home\Microsoft\dotnet\cli\dotnet.exe" arguments=".\..\approot\mydummycisite.dll" stdoutLogEnabled="true" stdoutLogFile=".\..\logs\stdoutcm" startupTimeLimit="3600" />
  </system.webServer>
</configuration>
```

Am i doing something wrong, or AspNetCoreModule still in the forge in Azure?

**Comment by muratg** [comment] 2016-04-19 16:16
I don' think AspNetCoreModule is available on Azure App Service yet.  @shirhatti?

**Comment by LeandroPT** [comment] 2016-04-19 16:25
@muratg @shirhatti 

It didn't complain about the module... As you can see by the log file... and process explorer shows it running dotnet.exe...

**Comment by moozzyk** [comment] 2016-04-19 16:28
This is fishy... If AspNetCoreModule had not been installed the application would not have been started... You would get 502 or something to this effect.

**Comment by muratg** [comment] 2016-04-19 16:41
Ah, perhaps the App Service roll out is completed after all.

**Comment by LeandroPT** [comment] 2016-04-19 16:49
@moozzyk @muratg 

Yeah, but why no response to browser? Request get to kestrel, response is return from kestrel... why no reach the browser? Will @shirhatti  have an idea?

**Comment by muratg** [comment] 2016-04-19 16:59
@BrennanConroy is giving this a try... @LeandroPT I assume you're using a simple HelloWeb or HelloMvc app?

**Comment by LeandroPT** [comment] 2016-04-19 17:13
@muratg 

No.. My RC2 MVC app. But you guys can check with those, all i need is confirmation that is ready. As you saw by the posts in this, i assumed it was not installed too.

I tested with both netcoreapp1.0 (the config above) and a net451 .exe
Both have the same outcome.

**Comment by shirhatti** [comment] 2016-04-19 18:59
@muratg  Azure App Service performs a rolling deployment. I believe they are currently in the process of rolling out ANCM. YMMV till they finish their deployment.

**Comment by LeandroPT** [comment] 2016-04-19 19:45
@shirhatti 

You abbreviations almost killed med... Where can that progress be tracked?

**Comment by BrennanConroy** [comment] 2016-04-20 19:28
What is your actual issue?
ANCM is being deployed so some Web Apps may have it and others might not. In your case you have it 👍

**Comment by BrennanConroy** [comment] 2016-04-22 23:02
No reply, closing

**Comment by LeandroPT** [comment] 2016-04-27 11:45
@BrennanConroy 

The issue still remains and the answer to your question is on the 1st post, and my life is already complicated to have you set me SLA's for replies.

I did some more tests and this is what i found out:

Picked project IISSamples on this repository as of TODAY, tweaked the project.json
[project.json.txt](https://github.com/aspnet/IISIntegration/files/238547/project.json.txt)

:

Running in **LOCAL IIS**: **https://localhost:4431/**
`Hello World - 27/04/2016 12:13:59 +01:00

Address:
**Scheme: https**
Host: localhost:4431
PathBase: 
Path: /
Query: 

Connection:
RemoteIp: ::1
RemotePort: 20342
LocalIp: 127.0.0.1
LocalPort: 1506
ClientCert: `


Running on Azure: **https://app-tst.azurewebsites.net**
`Hello World - 4/27/2016 11:23:39 AM +00:00

Address:
**Scheme: http**
Host: app-tst.azurewebsites.net
PathBase: 
Path: /
Query: 

Connection:
RemoteIp: 127.0.0.1
RemotePort: 50115
LocalIp: 127.0.0.1
LocalPort: 3331
ClientCert: 

Headers:
Cache-Control: no-cache
Connection: Keep-Alive
Pragma: no-cache
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,fr;q=0.6,pt;q=0.4
Cookie: ARRAffinity=563f2aa954e138962d8a339b4323e825f5b3199e8a68887dd820180b7bbcd76c
Host: app-tst.azurewebsites.net
Max-Forwards: 10
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
Upgrade-Insecure-Requests: 1
X-LiveUpgrade: 1
X-ARR-LOG-ID: 107216c4-474a-4f81-8e80-187bdc5feef9
DISGUISED-HOST: app-tst.azurewebsites.net
X-SITE-DEPLOYMENT-ID: app__6a69
X-Original-URL: /
X-Forwarded-For: 213.205.83.20:21003, 213.205.83.20:21003
X-ARR-SSL: 2048|256|C=US, S=Washington, L=Redmond, O=Microsoft Corporation, OU=Microsoft IT, CN=Microsoft IT SSL SHA2|CN=*.azurewebsites.net
MS-ASPNETCORE-TOKEN: 4ddcc54e-59b2-414a-b4fc-c4e5d3973a57
X-Forwarded-Proto: https
`

Since i have a requireHttps attribute on all controllers, it keeps on redirecting because what apparently in Azure is reaching Kestrel is HTTP and not https.

The Browser then gets `Failed to load resource: net::ERR_TOO_MANY_REDIRECTS`

So this is the CURRENT and as of NOW issue and apparently the aspnetcore module has different behavior on Azure App vs Local IIS

Anything else i need to provide?

**Comment by Tratcher** [comment] 2016-04-27 16:17
I see your issue now. You have two entries in X-Forwarded-For and only one in X-Forwarded-Proto. Our x-fowarded logic requires that there be the same number of entries in each of these headers.

You can override it by disabling x-forwarded-for like this:
```
            services.Configure<ForwardedHeadersOptions>(options =>
            {
              options.ForwardedHeaders = ForwardedHeaders.XForwardedProto
            });
```

@pan-wang can you investigate why there are two x-fowarded-for entries with the same value in Azure?

**Comment by LeandroPT** [comment] 2016-04-28 23:36
@Tratcher 

Your "hack" works perfectlly. I have made it using an appsettings switch, so as soon @pan-wang  has news, please let me know.

**Comment by Eilon** [comment] 2016-04-29 15:52
@Tratcher @muratg is there anything left for RC2 here?

**Comment by Tratcher** [comment] 2016-04-29 15:57
I've asked @pan-wang to investigate why there are duplicate X-Forwarded-For headers, but that can wait. Moving to 1.0.0

**Comment by rustd** [comment] 2016-05-13 18:04
Due to this all https scenarios are broken with Azure Web Apps.
All of the ASP.NET templates for Work & School Accounts are also broken as follows:
- Create a Web App with Work & School Account
- Publish to Azure Web Apps
- Browse to the site and login
- Login fails

**Comment by pan-wang** [comment] 2016-05-13 18:13
You can see ARR is enabled at Azure. I suspect the additional X-Forward-For header is added by ARR which also does the request forwarding. Will verify it with private test.

**Comment by Tratcher** [comment] 2016-05-13 18:50
This causes redirect based login flows like OIDC and OAuth to fail because the redirect url must be pre-registered with the provider (AAD), and login fails if it does not match.

**Comment by Tratcher** [comment] 2016-05-13 21:17
From what we can see the individual pieces are all working as expected, they just have different expectations from each other. We'll need to decide which component needs to change.

Flow:
ARR adds X-Forwarded-For
ANCM adds X-Forwarded-For and X-Forwarded-Proto
ForwardedHeadersMiddleware reads X-Forwarded-For and X-Forwarded-Proto and rejects then because the entry count does not match.

What does Nginx do?

**Comment by shirhatti** [comment] 2016-05-13 21:24
For Nginx you have explicitly set what headers you want in your config file, e.g.,

```
  location / {
    proxy_pass            http://localhost:80;

    proxy_set_header      X-Real-IP         $remote_addr;
    proxy_set_header      X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header      X-Forwarded-Proto https;
    proxy_set_header      X-Forwarded-Port  443;
    proxy_set_header      Host              $host;

  }
```

**Comment by Tratcher** [comment] 2016-05-13 21:27
Yeah, I found this sample which seems like a common recomendation: https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-load-balancing-with-ssl-termination

**Comment by Tratcher** [comment] 2016-05-18 20:51
Plan:
- Add an option to ForwardedHeadersMiddleware to disable the count check: https://github.com/aspnet/BasicMiddleware/issues/37
- Have UseIISIntegration check if it's running in Azure and disable the count check by default.

In parallel we'll investigate with Azure Web Sites to see if they can improve their setting of these headers.

**Comment by Tratcher** [comment] 2016-05-23 16:24
IsAzure check: https://github.com/aspnet/DataProtection/blob/8503e161d061fa230b00ba58d6801d7f906356ce/src/Microsoft.AspNetCore.DataProtection/Repositories/FileSystemXmlRepository.cs#L158-L162

**Comment by Tratcher** [comment] 2016-05-23 23:08
Fixed in nightly dev builds.

**Closed by Tratcher** 2016-05-23 23:08 UTC
Labels: 3 - Done, bug

**Comment by PinpointTownes** [comment] 2016-05-24 02:15
> Have UseIISIntegration check if it's running in Azure and disable the count check by default.

Hum, why not just disabling symmetry by default for all environments?

The errors caused by the lack of symmetric (e.g invalid `redirect_uri` during an OIDC request) are really hard to debug, specially since the log message associated with this error is not helpful at all and requires a high level of verbosity: `Failed to parse forwarded [header]`.

**Comment by Tratcher** [comment] 2016-05-24 17:08
We'll consider it if this comes up in most environments. For now we're using the most secure settings by default.
