### ISSUE TITLE
Error -4092 EACCES permission denied on WS2012R2+IIS

### ISSUE THREAD

**Issue by road42** [aspnet/IISIntegration#193] opened 2016-05-25 07:50 UTC
Hi, we get an "502 - Web server received an invalid response while acting as a gateway or proxy server." error with a ASP.NET Core RC2 default project app.

Server is Windows Server 2012 R2 with IIS installed as shown on docs.asp.net.

![apppool](https://cloud.githubusercontent.com/assets/3525089/15531944/70a92b1c-225d-11e6-812b-52835fec1276.png)

EventLog: 

`Failed to start process with commandline 'dotnet .\WebApp1.dll', Error Code = '0x80004005'.
`
LogFile: 
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Error -4092 EACCES permission denied) ---> Microsoft.AspNetCore.Server.Kestrel.Networking.UvException: Error -4092 EACCES permission denied
   at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.Check(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Http.TcpListener.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Http.Listener.<>c.<StartAsync>b__6_0(Object state)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at WebApp1.Program.Main(String[] args)
```

Web.Config:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <!--
    Configure your application settings in appsettings.json. Learn more at http://go.microsoft.com/fwlink/?LinkId=786380
  -->
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\WebApp1.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false"/>
  </system.webServer>
</configuration>
```

I wonder if its a kind of "netsh http urlacl ..."-thing with IIS. 
I also tried to run the apppool under an adminaccount.

**Comment by Tratcher** [comment] 2016-05-25 12:56
Please share your Program.Main, it's probably an issue with how you set up urls.

**Comment by road42** [comment] 2016-05-25 13:07
```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;

namespace WebApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
    }
}
```

**Comment by road42** [comment] 2016-05-25 13:10
I also tested on a local Windows 10/IIS10 without any issues.

**Comment by Tratcher** [comment] 2016-05-25 14:31
Actually, I think this is a duplicate of https://github.com/aspnet/IISIntegration/issues/176.

**Comment by road42** [comment] 2016-05-25 17:44
I think, you're right. The page was hosted under: http://app.sgr.lan/WebApp1 the same site under: http://xxx.sgr.lan/WebApp1 works.

**Closed** 2016-05-25 17:57 UTC
Labels: duplicate

**Comment by road42** [comment] 2017-12-28 11:36
The issue is about one year old and was a duplicate as written. The problem was fixed one release later.
