### ISSUE TITLE
Update ANCMv2 installer to install to ProgramFiles instead of inetsrv

### ISSUE THREAD

**Issue by shirhatti** [aspnet/IISIntegration#820] opened 2018-05-07 19:12 UTC

**Comment by rockerinthelocker** [comment] 2018-05-10 22:49
Historically, IIS modules are located under 'inetsrv' and you guys should keep it that way -- and there a lot good reasons for it. Sure, feel free to reinvent the wheel and learn lessons the hard way. Thank you!

**Comment by jkotalik** [comment] 2018-05-10 23:02
@rockerinthelocker I agree with you. From a purity and organization standpoint, keeping it in inetsrv is a better decision. The only benefit I saw is we can version based on the folder name rather than the dll name. Do you happen to know other good reasons for keeping it in inetsrv?

@pan-wang @shirhatti I'm not convinced that moving it to Program Files will help more than it will hurt. Changing a paradigm isn't worth it IMO.

**Comment by pan-wang** [comment] 2018-05-10 23:19
The trend for IIS oob is to install the binaries under program folder instead of instant,  e.g., ARR.  The reason is that we saw a lot of issues for Windows upgrade as the inetsrv folder get reset during upgrade  and IIS upgrade code have to specially treat the OOB modules in a known list, e.g., urlrewrite module.  Moving away from inetsrv folder helps in the upgrade scenario as windows will preserve the program folder.

**Comment by rockerinthelocker** [comment] 2018-05-11 04:16
@jkotalik , Simply adding a folder to 'inetsrv' with version folders underneath (i.e. aspnetcore\v2, aspnetcore\v3, etc.) should do the trick. Sure, there are some reasons. All-in-one-place experience, hassle-free (scripted/XCopy) deployment/restore of modules, no need to extend AV folder-exclusion lists, no need to update maintenance/monitoring scripts, you name it. Thank you!

@pan-wang , It's up to the Windows team to try harder to get the job done. Windows upgrades are still a nightmare and fixing a few issues, if any, related to IIS is nothing compared to the other issues caused by upgrades. In the worst case, customers (server administrators) simply restore the ANCM module from backup.

**Comment by shirhatti** [comment] 2018-05-11 17:58
> It's up to the Windows team

Some of us here are part of the Windows team 😄.

Deploying bits inside the Windows directory has ramifications and needs custom logic to handle Windows upgrade scenarios.
We've been burned by mistakes we've made here in the past. We would be none the wiser to ignore that. While it deploying native modules outside inetsrv might seem jarring to you, we've successfully employed with other IIS modules like ARR.

> In the worst case, customers (server administrators) simply restore the ANCM module from backup

I'm sure we all agree, we'd rather it not even come to that.

**Comment by rockerinthelocker** [comment] 2018-05-12 13:29
@coolcsh , Quite a number of custom and OOB IIS modules are stored under 'inetsrv' so abusing the Program Files folder as container for a couple of DLLs is highly questionable, right? Also, there is no guarantee that a Windows Upgrade (Web hosts certainly will block upgrades on production servers) will not break anything installed under Program Files. Thank you!

**Closed** 2018-06-20 18:11 UTC
Labels: 3 - Done
