### ISSUE TITLE
502.3 bad gateway errors couple of hours after deployment 

### ISSUE THREAD

**Issue by thisissubbuster** [aspnet/IISIntegration#323] opened 2017-02-10 11:21 UTC
I deployed an asp.net core 1.0 webapi service to Azure web app in Standard tier. It works fine for a couple of hours. But starts throwing **502.3 bad gateway** errors after that. Restarting the web app again fixes it. But it again behaves the same after some time. We deploy the service from VSTS. Please help

**Comment by GuardRex** [comment] 2017-02-10 15:39
Have you checkout out related issues and comments like https://github.com/aspnet/IISIntegration/issues/311, https://github.com/aspnet/IISIntegration/issues/269, and https://github.com/aspnet/IISIntegration/issues/245#issuecomment-242541999? You might have a different problem, but it's worth a read if you haven't seen it. Search the open & closed issues with "502.3" to get them to come up.

**Comment by thisissubbuster** [comment] 2017-02-11 09:00
Checked them out but still having the same issue. Let me know if you want to have a look at my files

**Comment by BrianVallelunga** [comment] 2017-02-14 20:07
I'm also having severe issues with an ASP.NET Core 1.1 app running .NET Core on Azure. Everything is fine, but then we'll suddenly have a huge spike in threads being used and the server will throw 502 errors.

Here's a screenshot of a good instance and a bad instance:

![dotnet threads](https://cloud.githubusercontent.com/assets/351190/22946763/5e4d7b6e-f2c6-11e6-8233-b4323b6dcd8f.PNG)

Here's the graph of threads being used by dotnet.ext

![threads](https://cloud.githubusercontent.com/assets/351190/22946781/71614f78-f2c6-11e6-9226-4835f84605ba.PNG)

And the graph of what happens to our site when this occurs:

![requests and errors](https://cloud.githubusercontent.com/assets/351190/22946801/8a2729f6-f2c6-11e6-83ee-510e04128c2a.PNG)

I took a memory dump of the w3wp and dotnet.exe processes if that will help diagnose the issues. I've read through most of the other threads linked but none of them has a definite solution that I can implement.

The site basically takes in form posts, transforms the data and posts messages onto Azure Service Bus. It also pulls back some data from Redis and returns it. Overall, it's quite basic.

I've seen references to some things being fixed in 1.1.1, but I haven't seen an ETA on when that will be released. I'm open to suggestions on immediate fixes.

**Comment by Tratcher** [comment] 2017-02-14 20:19
@halter73?

**Comment by nemenos** [comment] 2017-02-16 06:30
Yes, we have same issue and I need them fixed asap, or find a workaround. 
Hoping it's the problem fixed in 1.1.1... ETA?

**Comment by halter73** [comment] 2017-02-16 23:55
@BrianVallelung @nemenos  The increasing number of threads might have been caused by a [deadlock in Kestrel](https://github.com/aspnet/KestrelHttpServer/issues/1365#issuecomment-280164319). The best way to verify this is to to take a memory dump and use [VS's Debug Managed Memory Feature](https://github.com/aspnet/IISIntegration/issues/245#issuecomment-253668589) to take a look at the parallel stacks windows to see if it contains the same stacks as the screenshot in the linked Kestrel issue.

If the stacks do look the same. You can work around this issue by not using the ASP.NET Core to serve static files, and serve files directly using IIS as suggested [here](https://github.com/aspnet/IISIntegration/issues/311#issuecomment-278838271). This works, because in a typical app, the only thing that passes a CancellationToken to Response.WriteAsync() is the static file middleware. The deadlock will be fixed in 1.1.1 and in a 1.0.x backport which will be released [soon](https://github.com/aspnet/KestrelHttpServer/issues/1365#issuecomment-280164319).

**Comment by thisispaulsmith** [comment] 2017-02-17 11:52
We're experiencing exactly the same issue. If 1.1.1 fixes it then it can't come soon enough.

**Comment by cesarbs** [comment] 2017-03-14 01:01
1.1.1 is now out there. Anyone still experiencing the hang?

**Comment by BrianVallelunga** [comment] 2017-04-05 19:53
My issues seem mostly resolved. I ended up having to switch to the full framework due to needing Azure Service Bus support. We've been running ASP.NET Core + Full Framework for a couple of weeks without issue.

**Closed** 2017-04-26 19:02 UTC
