### ISSUE TITLE
EPIPE broken pipe

### ISSUE THREAD

**Issue by mejje** [aspnet/IISIntegration#298] opened 2016-11-10 08:11 UTC
This error is being logged to stdout on Azure from time to time:

`info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://thelogbook.eu/fonts/pe-icon-7-stroke/css/helper.css  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css'. Physical path: 'D:\home\site\wwwroot\wwwroot\fonts\pe-icon-7-stroke\css\pe-icon-7-stroke.css'
fail: Microsoft.AspNetCore.Server.Kestrel[0]
      TcpListenerPrimary.OnConnection
Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4047 EPIPE broken pipe
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.Check(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.write2(UvRequest req, UvStreamHandle handle, uv_buf_t* bufs, Int32 nbufs, UvStreamHandle sendHandle, uv_write_cb cb)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvWriteReq.Write2(UvStreamHandle handle, ArraySegment``1 bufs, UvStreamHandle sendHandle, Action``4 callback, Object state)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.DispatchConnection(UvStreamHandle socket)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.OnConnection(UvStreamHandle listenSocket, Int32 status)`

When it occur, the request is not terminated, but kept open until the two minute AspnetCoreModule 502 timeout happens (no data is being sent).

**Comment by davidfowl** [comment] 2016-11-10 08:28
This is a dupe of https://github.com/aspnet/KestrelHttpServer/issues/1182

**Closed by davidfowl** 2016-11-10 08:28 UTC
