### ISSUE TITLE
Unable to bind to the underlying transport for [PORT]. The IP Listen-Only list may contain a reference to an interface which may not exist on this machine.

### ISSUE THREAD

**Issue by sepehr1014** [aspnet/IISIntegration#778] opened 2018-04-16 07:24 UTC
We're using ASP.NET Core 2.1 Preview2 Final with IIS on Windows Server 2016. Once or twice a week, there comes a time when all request get `502 - Web server received an invalid response while acting as a gateway or proxy server. There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.` and nothing responds until we manually kill w3wp process.

The event logs are flooded with `HttpEvent: Unable to bind to the underlying transport for [::]:53362. The IP Listen-Only list may contain a reference to an interface which may not exist on this machine.  The data field contains the error number.`

```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-HttpEvent" Guid="{7b6bc78c-898b-4170-bbf8-1a469ea43fc5}" EventSourceName="HTTP" /> 
  <EventID Qualifiers="49152">15005</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-04-16T06:52:26.351608200Z" /> 
  <EventRecordID>79646</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="4" ThreadID="5996" /> 
  <Channel>System</Channel> 
  <Computer>WIN-VATCEK1C51C</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="DeviceObject" /> 
  <Data Name="Address">[::]:53362</Data> 
  <Binary>0000040002003000000000009D3A00C0000000000000000000000000000000000000000000000000430000C0</Binary> 
  </EventData>
  </Event>
```

I also took a dump of the worker process if it helps.

**Comment by sepehr1014** [comment] 2018-04-18 06:30
We're severely impacted by this issue. Any workarounds?

**Comment by pan-wang** [comment] 2018-04-23 23:38
do you have an IIS site bind to port 53362?  The port range 49152–65535 (215 + 214 to 216 − 1) is used for private or customized services, for temporary purposes, and for automatic allocation of ephemeral ports. Have  you tried other port?

**Comment by sepehr1014** [comment] 2018-04-25 08:01
@pan-wang We do not have any site bound to that port and I checked `netstat`, no other program was listening to that port either. How can I try another port? I thought it automatically chooses an arbitrary port on startup since when I kill the worker process and it starts again, everything's fine.

**Comment by pan-wang** [comment] 2018-04-25 21:39
ANCM only picks up the port number between 1024 and 48000. In the case of failure, could you please check whether the backend Kestrel was started and the application events with source "IIS AspnetCore Module" in windows event log?

**Comment by shirhatti** [comment] 2018-05-04 18:59
Hi. We're closing this issue as no response or updates have been provided   in a timely manner and we have been unable to reproduce it. If you have more   details and are encountering this issue please add a new reply and re-open   the issue.

**Comment by xs2bharat** [comment] 2018-05-09 18:35
for me. the solution was here for above issue. https://programmingflow.com/2015/08/28/solved-iis-express-failed-to-register-url-access-is-denied.html

**Comment by sepehr1014** [comment] 2018-05-19 20:27
We're also seeing

```
System.Net.Sockets.SocketException: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   at System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)
   at System.Net.Sockets.Socket.PostOneBeginConnect(MultipleAddressConnectAsyncResult context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)
   at System.Net.Sockets.Socket.DoDnsCallback(IAsyncResult result, MultipleAddressConnectAsyncResult context)
   at System.Net.Sockets.Socket.DnsCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
```

We're using web sockets. Might that be related? Maybe they're not successfully disconnected and the port status is waiting ...

**Comment by sepehr1014** [comment] 2018-06-01 07:01
@shirhatti @pan-wang We're still having this issue. Please reopen. The only log we have is:

`Unable to bind to the underlying transport for [::]:63883. The IP Listen-Only list may contain a reference to an interface which may not exist on this machine.  The data field contains the error number.`

The port number (63883) is different in each log obviously.

**Comment by shirhatti** [comment] 2018-06-01 16:50
@halter73 Does the Sockets stack trace above ring a bell?

**Comment by halter73** [comment] 2018-06-01 17:46
@shirhatti I haven't seen either of these errors before.

@sepehr1014 I see the SocketException is coming from TcpClient. Is this error coming from a client?

**Comment by sepehr1014** [comment] 2018-06-05 08:44
@halter73 No, but we use a HttpClient to send requests to google FCM and some other services ...

**Comment by shirhatti** [comment] 2018-06-05 16:57
@sepehr1014 This doesn't sound like a server issue. Given that you're using HttpClient, I suspect you're disposing it too frequently. This sounds like an ephemeral port exhaustion issue.

**Comment by sepehr1014** [comment] 2018-06-05 18:19
Quite the contrary. We're using only one static HttpClient so it's actually
never disposed. I suspect it has something to do with the disposal of
WebSockets since we heavily use them for our messaging features. BTW there
are no other web apps on this server.

**Comment by muratg** [comment] 2018-06-08 21:16
@pan-wang is talking to @sepehr1014 over email on this issue, so assigning this as an investigate item to him.

**Comment by pan-wang** [comment] 2018-08-24 17:34
@sepehr1014  I think this has same root cause as #854 . My understadning is that the workaround worked. V2.2 should contain a solid fix for this connection issue. Close it. Feel free to reopen it if you hit it with new ANCM bits

**Closed by pan-wang** 2018-08-24 17:34 UTC
Labels: investigate
