### ISSUE TITLE
ANCM: configuration change is not immediately notified until active requests are completed

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/IISIntegration#605] opened 2018-02-22 01:39 UTC
REPRO STEP
1. download a large file, which takes a long time
2. while downloading the file, change configuration

EXPECTED:

The configuration change is notified to ANCM and it should recycle app

ACTUAL:

The configuration change is not notified to ANCM until the file downloading is finished. This is because we use GLOBAL_MODULE::OnGlobalApplicationStop instead of GLOBAL_MODULE::OnGlobalApplicationStop

NOTE:
1. We have a similar issue with active WebSocket connections. If there is active websocket connections, changing configuration does not recycle app immediately and that is postponed after the app is being idle.
2. One work-around is to put app_offline.htm to force the app being recycled.

**Comment by shirhatti** [comment] 2018-02-26 22:25
Dupe of #608

**Closed by shirhatti** 2018-02-26 22:25 UTC
