### ISSUE TITLE
Tests failing with framework not found

### ISSUE THREAD

**Issue by pakrym** [aspnet/IISIntegration#875] opened 2018-05-25 23:09 UTC
https://github.com/aspnet/IISIntegration/pull/872

```
   | [2018-05-25T22:55:52] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Application ready at URL: http://localhost:54999/
   | [2018-05-25T22:55:52] Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.StartupTests Debug: Method: GET, RequestUri: 'http://localhost:54999/HelloWorld', Version: 2.0, Content: <null>, Headers:
   |                                                                                                      {
   |                                                                                                      }
   | [2018-05-25T22:55:52] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: IncrementMessages called
   | [2018-05-25T22:55:52] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Request started: "GET" http://localhost:54999/HelloWorld
   | [2018-05-25T22:55:53] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr: It was not possible to find any compatible framework version
   | [2018-05-25T22:55:53] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr: The specified framework 'Microsoft.NETCore.App', version '2.2.0-preview1-26509-06' was not found.
   | [2018-05-25T22:55:53] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr:   - Check application dependencies and target a framework version installed at:
   | [2018-05-25T22:55:53] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr:       C:\Program Files\IIS Express\
   | [2018-05-25T22:55:53] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr:   - Installing .NET Core prerequisites might help resolve this problem:
   | [2018-05-25T22:55:53] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr:       http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
   | [2018-05-25T22:55:53] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr:   - The .NET Core framework and SDK can be installed from:
   | [2018-05-25T22:55:53] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr:       https://aka.ms/dotnet-download
   | [2018-05-25T22:55:53] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Request ended: http://localhost:54999/HelloWorld with HTTP status 500.0
   | [2018-05-25T22:55:53] Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.StartupTests Warning: StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
   |                                                                                                        {
   |                                                                                                          Cache-Control: private
   |                                                                                                          Server: Microsoft-IIS/10.0
   |                                                                                                          X-SourceFiles: =?UTF-8?B?QzpcVXNlcnNccnVubmVyXEFwcERhdGFcTG9jYWxcVGVtcFxkOTA5MmExNS0yMzhjLTQ4OTktYjY3MS01MmI1ZDRkMGE5YjdcSGVsbG9Xb3JsZA==?=
   |                                                                                                          X-Powered-By: ASP.NET
   |                                                                                                          Date: Fri, 25 May 2018 22:55:53 GMT
   |                                                                                                          Content-Type: text/html; charset=utf-8
   |                                                                                                          Content-Length: 5821
   |                                                                                                        }
```

https://github.com/aspnet/IISIntegration/pull/865

```
| [1.839s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: IncrementMessages called
| [1.841s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Request started: "GET" http://localhost:64180/
| [1.888s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr: It was not possible to find any compatible framework version
| [1.888s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr: The specified framework 'Microsoft.NETCore.App', version '2.2.0-preview1-26524-01' was not found.
| [1.888s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr:   - Check application dependencies and target a framework version installed at:
| [1.889s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr:       C:\Program Files (x86)\IIS Express\
| [1.889s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr:   - Installing .NET Core prerequisites might help resolve this problem:
| [1.889s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr:       http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
| [1.889s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr:   - The .NET Core framework and SDK can be installed from:
| [1.889s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr:       https://aka.ms/dotnet-download
| [1.890s] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Request ended: http://localhost:64180/ with HTTP status 500.0
```

**Comment by Tratcher** [comment] 2018-05-25 23:11
Primarily Win7/2008R2 http://aspnetci/project.html?projectId=XPlat&testNameId=-5755570781948725031&tab=testDetails

**Comment by jkotalik** [comment] 2018-06-01 05:39
Found the root cause of this. It's a null ref on the application exe. Will make a PR tomorrow.

**Comment by jkotalik** [comment] 2018-06-01 19:01
@shirhatti moving this into next week too (as it may not be done by EOD).

**Comment by jkotalik** [comment] 2018-06-04 22:08
Will continue monitoring CI for failures on Win7 (if failures persist, will investigate further).

**Comment by jkotalik** [comment] 2018-06-05 00:41
Things still on fire and I started getting this failure locally. Seems flaky, but most likely a product issue.

**Comment by jkotalik** [comment] 2018-06-06 00:02
Follow up issue filed #888 . This issue seems to be resolved.

**Closed by jkotalik** 2018-06-06 00:02 UTC
Labels: 2 - Working, cost: S
