### ISSUE TITLE
HTTP Error 502.5 - Process Failure

### ISSUE THREAD

**Issue by ferdelfino** [aspnet/IISIntegration#256] opened 2016-09-02 18:28 UTC
Hi, I'm having a problem with a portable app hosted on IIS.  If I start it from command line it works but IIS cannot do it, 
The event viewer shows this error -> Failed to start process with commandline '"dotnet" .\WebApps.dll', ErrorCode = '0x80070002'.
I've went through the list of possible causes here (https://docs.asp.net/en/latest/publishing/iis.html#common-errors) and everything looks good.
Thanks!

**Comment by GuardRex** [comment] 2016-09-02 21:15
@Tratcher @shirhatti @moozzyk After chatting with @t-delff on Slack, I thought it might be along the lines of https://github.com/aspnet/IISIntegration/issues/228, but there don't seem to be any obvious access problems for the App Pool identity in this case. I suggested to @t-delff to open here for additional discussion.

**Comment by moozzyk** [comment] 2016-09-02 22:04
0x80070002 is file not found. Maybe use process monitor which file it is trying to access and can't find? In the early days IIS in some cases could not find schema for HttpPlatformHandler and we figured it out this way.

**Comment by GuardRex** [comment] 2016-09-02 22:10
@t-delff Your `web.config` is at the app base path (same folder as the app's DLL), correct? https://docs.asp.net/en/latest/hosting/directory-structure.html

**Comment by t-delff** [comment] 2016-09-02 22:11
Yes, both web.config and app.dll are on the root folder and the same used for the Virtual inside the Web Site

**Comment by GuardRex** [comment] 2016-09-02 22:16
> same used for the Virtual inside the Web Site

Do you have two `web.config` files at play then? If so, the sub-app `web.config` shouldn't have a `<handlers>` section.

**Comment by t-delff** [comment] 2016-09-02 22:22
No, the web site don't have a web.config.  I tried to use a website first but then I moved to a virtual.

**Comment by GuardRex** [comment] 2016-09-02 22:24
Oh, ok. Just checking.

You could look and confirm based on what @moozzyk said and just make sure the schema file (`aspnetscore_schema.xml`) for the module is in position ...

![capture](https://cloud.githubusercontent.com/assets/1622880/18219781/020d62ee-7132-11e6-99bd-40689693767f.PNG)

**Comment by t-delff** [comment] 2016-09-02 22:28
Yes, it's in place
![image](https://cloud.githubusercontent.com/assets/21087258/18219866/711ff21c-7143-11e6-98ad-7ae41c04d304.png)
Should I check for a value inside it?

**Comment by GuardRex** [comment] 2016-09-02 22:45
Prob not the issue ... 3KB is the correct file size.

Other than what @moozzyk said about trying to figure out what it can't find with Process Monitor (a method that I'm not familiar with), I don't see why a file not found would occur.

You might want to try setting up the app as a self-contained app, which would eliminate firing the `dotnet` command directly:

1. Take `"type": "platform"` off of your `Microsoft.NETCore.App` dep in `project.json`.
2. Add a `runtimes` section with an RID like `win10-x64` in `project.json`. See example below.
3. Do a `dotnet restore`.
4. Publish with `dotnet publish -c Release -r win10-x64`. The `web.config` should say `processPath=".\WebApps.exe"` with no `arguments` attribute. 
5. Stop the AppPool, swap the published assets, then restart the AppPool.

That will remove the `dotnet.exe` call from the equation.

```json
"runtimes": {
    "win10-x64": {}
},
```

**Comment by moozzyk** [comment] 2016-09-02 22:51
I said in our case it was the schema file but I didn't think it was the case here since the error message you got was already from AspNetCoreModule so IIS must have loaded AspNetCoreModule correctly. What I tried to say was that you can use the same technique to figure out what file it is not able to load and this should give you a hint where to look.

**Comment by GuardRex** [comment] 2016-09-02 23:07
@moozzyk A side note to this issue but a good point to check for the next update to the Publish to IIS doc. I'd like to see what happens when the schema file is missing/corrupt (unloadable) and perhaps add that to the common errors.

@t-delff There is another general troubleshooting step that can sometimes clear a strange issue. In this case if the file that cannot be found has something to do with a missing published asset due to some odd issue with old packages or the `dotnet cli`, it won't harm anything and sometimes helps to nuke the package caches before getting a nice, fresh set of packages with `dotnet restore`.

I like using the `nuget locals all -clear` to clear caches (but you can do it manually). You can get the `nuget.exe` from NuGet.org. `dotnet restore` will then make sure everything is fresh.

... and one more thing: Check your NuGet feed. For my 1.0.0 projects, I explicitly set the feed in my `NuGet.Config` file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```
These general troubleshooting steps I've listed are probably not going to solve this issue; however, they have been known from time-to-time to clear a strange issue.

**Comment by moozzyk** [comment] 2016-09-02 23:11
@GuardRex - why would schema be missing  and why would it be a common error? You can probably already follow a common sense guideline like "if ANCM is not working correctly reinstall ANCM". The tricky part is to figure out the "ANCM is not working part" (vs. application misconfiguration)

**Comment by GuardRex** [comment] 2016-09-02 23:16
Point taken. I'm always looking for ways to make that section just a little bit better, but true, that's too exotic of an issue to sweat.

Also, ^^ my note above can't directly help (although not bad for @t-delff to see) when `dotnet` can run his app from the command line. There isn't much else tho, is there? ... The module ... the schema file ... the `web.config` ... the `dotnet` command ... and the DLL. What else could it even be possibly looking for on module side of this?

**Comment by moozzyk** [comment] 2016-09-02 23:22
permissions - IIS runs as a different user

**Comment by GuardRex** [comment] 2016-09-02 23:32
ah ... gotcha ... then perhaps something similar to #228 after all.

@t-delff Word from a :pray: server god :pray: is Process Monitor. This holiday weekend, don't forget to sacrifice a case of :beer: to @moozzyk! :smile:

I'm not familar with the approach, but a quick search turns up several explanations along the lines of http://www.codeproject.com/Articles/560816/Troubleshooting-dependency-resolution-problems-usi?msg=4515717

**Comment by moozzyk** [comment] 2016-09-03 01:14
Start proc mon. Stop capturing events (Ctrl + E). Filter by process name - my guess you will need w3wp.exe and dotnet.exe. Clear events (Ctrl +X). Start capturing events (Ctrl + E). Make a request to your app. Once it fails stop capturing events (Ctrl + E). Review the events. Inspect ones whose status is FILE NOT FOUND - you should see in the details what file it is trying to access and whether this can be the file that can be causing issues. You should also be able to find an entry for creating the dotnet.exe process review events related to this event. Hopefully this will give you a hint where the problem is.

**Comment by moozzyk** [comment] 2016-09-03 01:29
One more thought. Have you actually changed the global %PATH% to include the folder where `dotnet.exe` lives *and* restarted the server with iisreset.exe? Maybe the file that cannot be found is just the dotnet.exe and this is because it is not on the %path%? Note that you need to reset IIS hard for the change to %PATH% to be picked up.

**Comment by t-delff** [comment] 2016-09-05 18:21
@moozzyk, after reading your comment about hard reset on IIS I realized that the server wasn't restarted by IT so I requested it. Then, bingo, problem solved! 
Thank you and also thanks to @GuardRex, you were really helpful with the issue.

**Comment by GuardRex** [comment] 2016-09-05 18:33
> Have you actually changed the global %PATH% to include the folder where dotnet.exe lives and restarted the server with iisreset.exe?

I didn't think that would be a prob because it ran from the command line without the full path to `dotnet.exe`; however, I think @moozzyk is going to say that this has more to do with IIS picking it up than being able to access `dotnet` from the command line.

I need to add the line ...

> You may have deployed a portable application and installed .NET Core without restarting the server. Restart the server.

to the troubleshooting suggestions for the **Incorrect proecessPath, missing PATH variable, or dotnet.exe access violation** entry which matches the exception here. I'll get it in there asap (cc/ @Rick-Anderson). Thanks @t-delff for the issue and :beers: to @moozzyk for solving it.

**Comment by moozzyk** [comment] 2016-09-06 18:10
@GuardRex _I didn't think that would be a prob because it ran from the command line without the full path to dotnet.exe_ :arrow_right:  https://github.com/aspnet/IISIntegration/issues/256#issuecomment-244508991 (after dash)

**Comment by gilgenast** [comment] 2016-09-07 19:07
I’ve went through all the items contained in #common-errors section, still was getting 0x80070002 error with an empty log file.  No problems when running from command line using Application Pool account. I was restarting IIS server all the time. The last resort was to reboot the Windows Server. Voilà, it works!!!

**Comment by ferdelfino** [comment] 2016-09-07 19:09
That's exactly what happened to me, only Windows restart fixed it!

**Comment by GuardRex** [comment] 2016-09-07 19:15
@gilgenast @ferdelfino We'll need a clarification from @moozzyk.

**Comment by moozzyk** [comment] 2016-09-07 22:45
I think that restarting IIS from the management console does not cut it. If `iisreset` did not work then I don't know - I did observe that the changes to the global %PATH% were not picked up until I restarted IIS with `iisreset` but I did not have to reboot the box.

**Comment by GuardRex** [comment] 2016-09-07 23:07
I read a little on it, and it seems that one possible negative outcome of the command-line IISReset is how it shuts down services that don't shut themselves down in a timely fashion when the utility is run, which can lead to config changes not getting saved properly.

The options are ...
* Test thoroughly and see if iisreset and/or console work to preserve these options for admins if either or both work (b/c server admins may prefer to use these approaches over a full server restart), or ...
* Just assume that the best, safest approach is to instruct admins to do the restart and not to rely upon the utility or console ... and they just need to do the deal with it even if they don't like it.

WRT testing ... it would be easier for me to do that when we get to the 1.1 release, when I'm planning a big look and checkup on the doc. I'm buried in a big Xamarin project for the next two weeks.

**Comment by pan-wang** [comment] 2016-09-07 23:35
IIS worker process w3wp.exe is a child process of windows WAS service. If user wants w3wp to pick up some newly added PATH value, we always recommend user to do "net stop WAS" and then "net start w3svc". See this KB https://support.microsoft.com/en-us/kb/236166. Could you please address more about "config changes not getting saved properly"

**Comment by GuardRex** [comment] 2016-09-07 23:42
From this one: https://support.microsoft.com/en-us/kb/286196

Not that that is a problem specific to this situation. It just caught my eye that IISReset had an effect on IIS that was different than `net stop/net start` as they discuss in the workaround.

If you think it best that the guidance just say "restart the server," then I'm all good with that. Just let me know which way you want to go with the doc.

**Comment by pan-wang** [comment] 2016-09-08 00:49
iisreset is not supported on windows 7 and above per https://technet.microsoft.com/en-us/library/dd364067(v=ws.10).aspx. The recommendation is to call net stop and net start or reboot the server.

**Comment by GuardRex** [comment] 2016-09-08 00:56
Ah ... gotcha.

So the conclusion is to modify that doc language to say either (a) restart the server, or (b) execute `net stop` and `net start` from the command-line.

Are the commands more specific than that? i.e. ... `net stop iisadmin /y` and then `net start w3svc`, or it is just literally `net stop` and `net start`?

**Comment by moozzyk** [comment] 2016-09-08 03:24
Thanks @pan-wang. I did not know that.

**Comment by pan-wang** [comment] 2016-09-08 17:44
@GuardRex IIS7 and above have totally different configuration system compared with IIS6 and below.   Most content in the KB https://support.microsoft.com/en-us/kb/286196  is not applied to IIS7 and above, e.g.,  some services got renamed and some got deleted.   Back to your question, we should recommend specific command "net stop was /y" to stop iis services (automatically including w3svc) and then call "net start w3svc" to restart iis services.

**Comment by GuardRex** [comment] 2016-09-08 18:29
@pan-wang Cool. Is it ok to leave 'restart the server' as an option?

How about language like this for the instruction in the doc ...

> Restart the server or execute `net stop was /y` followed by `net start w3svc` from the command-line to pickup changes to the system PATH.

... and in troubleshooting ...

> You may have deployed a portable application and installed .NET Core without restarting IIS. Either restart the server or restart IIS by executing `net stop was /y` followed by `net start w3svc` from the command-line.

**Comment by muratg** [comment] 2017-05-12 21:26
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Closed by muratg** 2017-05-12 21:26 UTC

**Comment by degrootsde** [comment] 2017-08-16 18:20
Maybe completely off topic, but I encountered this same issue when I added a Dotnet Core host as an existing website to a solution. VStudio interpreted is as an .Net 2.0 application. 
It should be added as an existing project. Maybe this helps anyone looking for the 0x80070002 : 0 exception code.

**Comment by SenenFernandez** [comment] 2017-10-04 01:56
Check if [Visual C++ 2015 Redistributable][1] is installed =)


  [1]: https://my.visualstudio.com/Downloads?pid=2082
