### ISSUE TITLE
Flaky test: InvalidFilePathForLogs_ServerStillRuns - Shutdown Timeout

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/IISIntegration#1085] opened 2018-07-23 17:53 UTC
This test [fails](http://aspnetci/viewLog.html?buildId=512054&buildTypeId=XPlat_Windows_Win2008r2_Universe) occasionally with the following error:
```
System.TimeoutException : IIS failed to stop site HttpTestSite20180722211208.
   at Microsoft.AspNetCore.Server.IntegrationTesting.IISApplication.WaitUntilSiteStopped()
   at Microsoft.AspNetCore.Server.IntegrationTesting.IISApplication.StopAndDeleteAppPool() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISApplication.cs:line 141
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.Dispose() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 33
   at Microsoft.AspNetCore.Server.IntegrationTesting.FunctionalTestsBase.StopServer() in /_/test/Common.FunctionalTests/Utilities/FunctionalTestsBase.cs:line 48
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 76
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test InvalidFilePathForLogs_ServerStillRuns at 2018-07-23T04:12:08
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Deploying [Variation] :: ServerType=IIS, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Executing command dotnet publish  --output "C:\BuildAgent\temp\buildTmp\f2b22182-fd9b-45da-ad23-5eab21e51edb" --framework netcoreapp2.2 --configuration Release --no-restore -p:VerifyMatchingImplicitPackageVersion=false 
| [0.225s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
| [0.225s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
| [1.121s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout:   TestTasks -> C:\BuildAgent\work\33bdfc1cae7b2a38\modules\IISIntegration\test\TestTasks\bin\Release\netcoreapp2.2\TestTasks.dll
| [1.198s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout:   Microsoft.AspNetCore.Server.IIS -> C:\BuildAgent\work\33bdfc1cae7b2a38\modules\IISIntegration\src\Microsoft.AspNetCore.Server.IIS\bin\Release\netstandard2.0\Microsoft.AspNetCore.Server.IIS.dll
| [1.538s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout:   InProcessWebSite -> C:\BuildAgent\work\33bdfc1cae7b2a38\modules\IISIntegration\test\WebSites\InProcessWebSite\bin\Release\netcoreapp2.2\InProcessWebSite.dll
| [2.226s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout:   InProcessWebSite -> C:\BuildAgent\temp\buildTmp\f2b22182-fd9b-45da-ad23-5eab21e51edb\
| [2.269s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet publish finished with exit code : 0
| [2.271s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Backed up C:\Windows\system32\inetsrv\config\applicationhost.config to C:\Windows\system32\inetsrv\config\applicationhost.config.HttpTestSite20180722211208backup
| [2.278s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Copied contents of IIS.config to C:\Windows\system32\inetsrv\config\applicationhost.config
| [2.285s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Could not add environment variables to worker process: Filename: 
|                                                                                      Error: Unrecognized element 'environmentVariables'
| [2.286s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Configured AppPool HttpTestSite20180722211208Pool
| [2.286s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Configured Site HttpTestSite20180722211208 with AppPool HttpTestSite20180722211208Pool
| [2.286s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Could not find AspNetCoreModuleV2 section in global modules; creating section.
| [2.286s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Could not find AspNetCoreModuleV2 section in modules; creating section.
| [2.339s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Site HttpTestSite20180722211208 has started.
| [2.339s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Successfully finished IIS application directory setup.
| [2.341s] Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.LoggingTests Debug: Method: GET, RequestUri: 'http://localhost:54208/HelloWorld', Version: 2.0, Content: <null>, Headers:
|                                                                                         {
|                                                                                         }
| [3.435s] Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.LoggingTests Debug: StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
|                                                                                         {
|                                                                                           Transfer-Encoding: chunked
|                                                                                           Server: Microsoft-IIS/7.5
|                                                                                           Date: Mon, 23 Jul 2018 04:12:12 GMT
|                                                                                     
...
```

**Comment by Eilon** [comment] 2018-07-23 20:48
@jkotalik / @mikeharder - can one of you take a look at this flaky test?

**Comment by Eilon** [comment] 2018-07-25 20:22
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

@jkotalik - please use the workflow above to process this issue.

**Comment by jkotalik** [comment] 2018-07-25 22:30
https://github.com/aspnet/IISIntegration/issues/1098 for the first issue, https://github.com/aspnet/IISIntegration/pull/1096 for the second.

**Comment by ryanbrandenburg** [comment] 2018-07-30 01:07
Gets500_30_ErrorPage [failed again](http://aspnetci/viewLog.html?buildId=518392&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by mikeharder** [comment] 2018-08-09 22:27
This might be a product issue in ANCM blocking app shutdown, or it could be IIS just failing to shutdown for reasons unrelated to ANCM.  We should investigate adding more logging to `IISDeployer.Stop()` and/or `IISDeployer.WaitUntilSiteStopped()`.

**Comment by jkotalik** [comment] 2018-08-17 23:27
AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed is returning 0x80070002, which is file not found. May be related to app_offline being missing/present.

**Comment by muratg** [comment] 2018-08-23 22:06
Moving to preview2 since preview1 has already shipped.

**Comment by aspnet-hello** [comment] 2018-08-24 00:25
InvalidFilePathForLogs_ServerStillRuns [failed with about the same error](http://aspnetci/viewLog.html?buildId=537725&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment] 2018-08-25 00:52
InvalidFilePathForLogs_ServerStillRuns [failed with about the same error](http://aspnetci/viewLog.html?buildId=538895&buildTypeId=XPlat_Windows_Win7_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment] 2018-08-27 15:05
InvalidFilePathForLogs_ServerStillRuns [failed with about the same error](http://aspnetci/viewLog.html?buildId=539776&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by muratg** [comment] 2018-08-29 18:16
cc @pakrym

**Comment by pakrym** [comment] 2018-09-04 20:54
First occurances of this issue happened before IISDeployer rewrite that fixed a lot of deployment related failured and later ones are dotnet publish related mass failures that were fixed. Closing this issue.

**Closed by pakrym** 2018-09-04 20:54 UTC
Labels: Branch:2.2, Branch:master, test-failure
