### ISSUE TITLE
Failed to start process on Azure App Service, ErrorCode = '0x80004005 : c0020043

### ISSUE THREAD

**Issue by chrarnoldus** [aspnet/IISIntegration#836] opened 2018-05-14 22:45 UTC
We have a web app on Azure App Service that sometimes fails to start with the following error message:

```
Application 'MACHINE/WEBROOT/APPHOST/BLAHBLAH' with physical root 'D:\\home\\site\\wwwroot\\' failed to start process with commandline 'dotnet .\\BlahBlah.dll', ErrorCode = '0x80004005 : c0020043.
```

The error is intermittent; the app usually starts successfully a few minutes later. Requests will stall or timeout in the meantime, resulting in noticeable downtime.

Does anyone know what this error means or how to find out what it means? It does not seem to be documented [here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-iis-errors-reference?view=aspnetcore-2.0). Enabling stdout logging in web.config does _not_ result is any related error being logged (unrelated messages are being logged).

This is an ASP.NET Core 2.0 app running on .NET Core.

**Comment by muratg** [comment] 2018-05-16 20:29
@chrarnoldus Any chance you could share your csproj file?

- Does your app work well on your dev box? And only fail on App Service?
- Does your app ever succesfully return results on App Service, or zero `200`s? 

I wondering if it's a mismatch between the runtime you target and the runtime App Service has.

**Comment by chrarnoldus** [comment] 2018-05-16 20:58
Project file is here: https://gist.github.com/chrarnoldus/584439e0656c250231dee27a7bd8014a

> Does your app work well on your dev box? And only fail on App Service?

I've never seen the error on a devbox at least.

> Does your app ever succesfully return results on App Service, or zero 200s?

Yes, in fact it works fine most of the time, but sometimes requests start timing out and we find that line in the application events. The app will recover by itself in a few minutes.

> I wondering if it's a mismatch between the runtime you target and the runtime App Service has.

Not to derail, but we've seen other weird issues like `InvalidProgramException`s being thrown at seemly random places in code.

**Comment by Tratcher** [comment] 2018-05-16 23:57
This looks related: https://support.microsoft.com/en-us/help/312544/you-may-receive-an-invalidprogramexception-error-message-when-you-run
It gives some possible debugging steps.

To debug this on our side we'd need a full application that reproduces the issue.

**Comment by muratg** [comment] 2018-05-17 00:17
@chrarnoldus Yeah, your project file seems fine.  And my initial suspicion (possible runtime mismatch) was wrong.

@pan-wang any ideas?

**Comment by DamianEdwards** [comment] 2018-05-17 01:09
Could this be the port exhaustion issue again?

**Comment by pan-wang** [comment] 2018-05-17 01:44
@DamianEdwards  it could be. However, the process exit code 0x43 looks different. @chrarnoldus where did you see this InvalidProgramExceptions thrown? how many events did you saw in the failure case? have you tried enabling stdout log to capture the failure?

**Comment by chrarnoldus** [comment] 2018-05-17 15:35
> where did you see this InvalidProgramExceptions thrown?

https://gist.github.com/chrarnoldus/37a60f018e33983c1a7ac410c124d637

https://gist.github.com/chrarnoldus/e2e3a1651648a1a98c3a32b7e8911425

In both cases these exceptions would be continuously thrown on every request until the process restarted.

I doubt these are related to the error code (I just mentioned them because I thought they could be a symptom of running on an incompatible runtime). I could create a separate issue, but don't think there's much point in that considering I can't reproduce them consistently.

> how many events did you saw in the failure case?

Just the one mentioned, followed by a successful start. I don't see anything related to why the application shut down. The "App Restart Analysis" of App Service doesn't report anything either.

> have you tried enabling stdout log to capture the failure?

Yes, see initial post.

**Comment by chrarnoldus** [comment] 2018-05-17 15:38
> To debug this on our side we'd need a full application that reproduces the issue.

I don't have code that reproduces the exception consistently. I do have memory dumps captured by the Application Insights collector when they occurred.

**Comment by Tratcher** [comment] 2018-05-17 15:47
Dumps might be interesting.

**Comment by chrarnoldus** [comment] 2018-05-17 16:35
@Tratcher Can I share them securely? There's probably connection strings and private keys in there.

**Comment by Tratcher** [comment] 2018-05-17 16:38
Sure, you can put it in OneDrive or similar and share it with the e-mail in my profile.

**Comment by Tratcher** [comment] 2018-05-21 21:02
Taking a closer look at your dependencies, I do see a mismatch. 
`Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.2.1"` depends on `Microsoft.AspNetCore.Hosting (>= 1.0.2)`, but you're using `Include="Microsoft.AspNetCore.All" Version="2.0.7"`. @pakrym do you know what the right AI package to use here is?

**Comment by DamianEdwards** [comment] 2018-05-21 22:44
That's normal, the AI packages target the lowest supported version.

**Comment by chrarnoldus** [comment] 2018-06-06 13:29
I've created a separate issue for the InvalidProgramExceptions here: https://github.com/dotnet/coreclr/issues/18323. Because they are, as far as I can tell, unpredictable and all over the place I suspect the problem is in the runtime and not in ASP.NET Core.

**Comment by chrarnoldus** [comment] 2018-06-06 13:32
I must say I find the experience of debugging startup issues through the ASP.NET Core module a bit lacking, as many of the error codes don't seem to be documented and if you want the extra info provided by stdout logging you basically have to predict the error upfront, so you can turn it on in time.

**Comment by pakrym** [comment] 2018-06-06 19:02
@chrarnoldus  we are currently looking into improving diagnostic experience.

**Comment by Tratcher** [comment] 2018-06-21 16:59
Closing this as a duplicate of https://github.com/dotnet/coreclr/issues/18323

**Closed by Tratcher** 2018-06-21 16:59 UTC
