### ISSUE TITLE
Running ASP.NET 5 RC1 on Windows Web Server 2008 R2 - 502.3 error

### ISSUE THREAD

**Issue by grzech1983** [aspnet/IISIntegration#79] opened 2016-02-01 09:19 UTC
Hello,

I'm managing mixed 2008 R2, 2012 and 2012 R2 hosting environment managed by WebsitePanel control panel. I've started interesting in testing and adding possibility to run ASP.NET 5 RC1 and later versions (when they will be released). I've installed the same set of software httpPlatformHandler 1.2 and AspNet5.ENU.RC1_Update1.exe package on every system. On each system I'm publishing the same sample app from Visual Studio 2015 Community Edition (using WebDeploy) and now interesting part: this app worked out of the box on all 2012 and 2012 R2 systems but not on every of my 2008 R2 systems. Does anyone have any idea where to look for solution? I'm struggling with this for maybe a week, I've tried to narrow down issue using Process Monitor but still I don't know what is causing it. I have updated systems with latest Windows Update updates, I've tried multiple times to install httpPlatformHandler by downloading it using Web Platform Installer and directly from IIS website. HttpPlatformHandler version on 2008 R2 and 2012 systems is the same and it is 1.2.1959. I've tried to set stdoutLogEnabled to true but in logs directory is only created empty log file without any content. When website is being opened only w3wp.exe process is being started for it and event log contains event id 1000 entries for HttpPlatformHandler source with identical content:

```
The description for Event ID 1000 from source HttpPlatformHandler cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Process '87792' failed to start. Port = 11779, Error Code = '-2147024891'.
```

HttpPlatformHandler module is present in Modules visible in IIS Manager for local IIS server. Does anyone have any idea where to look for solution? Interesting part is that this is not working identical on all of 2008 R2 systems so IMHO this is not one system specific issue. I've tried to look for solution in a lot of places but mostly fix was updating HttpPlatformHandler to latest 1.2 version which will not work since I already use latest version.

Thanks

**Comment by grzech1983** [comment] 2016-02-04 10:54
Maybe this report should be moved or created under different category/project like https://github.com/aspnet/Hosting ?

**Comment by Tratcher** [comment] 2016-02-04 17:11
This is the right place. We're still getting used to HttpPlatformHandler and it's various error cases. Here is one of the better writeups sofar: https://github.com/aspnet/Hosting/issues/364#issuecomment-148567294

> 7. If you're on Windows 7 or WS 2008 R2, confirm you have Visual C++ Redistributable for Visual Studio 2012 Update 4 installed.

Have you confirmed that dependency?

**Comment by grzech1983** [comment] 2016-02-04 20:46
Hello,

thanks for responding. I saw somewhere else (maybe StackOverflow) mentioning about Visual C++ Redistributable and I've it installed for x64 and x86 with version 11.0.61030.0. I was trying to set app pool to x64 (since by default I'm using 32bit app pools), setting pool user with more permissions (even Administrator), setting it to no managed code too. Every try ended with error:

Error Summary
HTTP Error 502.3 - Bad Gateway
There was a connection error while trying to route the request.
Detailed Error Information
Module	httpPlatformHandler
Notification	ExecuteRequestHandler
Handler	httpplatformhandler
Error Code	0x80070005

Issue is identical on all three Windows Web Server 2008 R2 systems.

**Comment by dallancarr** [comment] 2016-02-04 20:58
Hope this is not the Webdav issue

**Comment by Tratcher** [comment] 2016-02-04 21:53
`0x80070005 (E_ACCESSDENIED)` sounds like a permissions issue. Is there a matching event in the EventViewer?

**Comment by grzech1983** [comment] 2016-02-05 09:17
Nope. There are only 20 event log Application errors with content:

```
The description for Event ID 1000 from source HttpPlatformHandler cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Process '228020' failed to start. Port = 13690, Error Code = '-2147024891'.

```

**Comment by grzech1983** [comment] 2016-02-05 11:14
One comment which looks similar to my issue is here:

https://github.com/aspnet/Hosting/issues/466#issuecomment-168372853

with info:

```
Try checking Windows event viewer, If you get "Process xxx failed to start. Port = yyy, Error Code = '-2147023829'.", please specify --runtime active option to include runtimes when creating artifacts using the dnu publish command tool.
```

but I'm not sure where I should specify this option since whole process is being made from VS where I'm importing publishing profile and publish app using WebDeploy directly to IIS server.

**Comment by Tratcher** [comment] 2016-02-05 14:42
They're referring to the command line steps for publishing. What are your actually publishing steps? Using VS to publish to the file system, with a specific runtime (who's bitness matches your app-pool), and clearing the contents of the output dir. Then copy that output to the web server, set permissions, etc..

**Comment by moozzyk** [comment] 2016-02-05 18:29
One way to troubleshoot issues when the application can be start as the current user and won't start with IIS is to try to start application as a different user who does not have all dev settings set. Just publish the app to a folder accessible to everyone (or just use the same folder you published for IIS) and start a cmd using the runas command and try to start the application.

**Comment by niclasebs** [comment] 2016-02-11 12:07
I am not sure if this is going to help, I was however struggling to find the cause of an exception like that when I published a new version of my vnext app to IIS, w3wp.exe was crashing and event log gave me this: HttpPlatformHandler: "The description for Event ID 1000 from source HttpPlatformHandler cannot be found".

This occurred when I changed the web command in my project.json from:
`"web": "Microsoft.AspNet.Server.Kestrel"`
to
`"web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000"`

**Comment by Tratcher** [comment] 2016-02-11 12:12
@niclasebs The lack of WebListener support is a known issue: https://github.com/aspnet/IISIntegration/issues/8

**Comment by grzech1983** [comment] 2016-02-12 09:48
It looks like I will have to update my 2008 systems to 2012 R2. I should done this long time ago anyway.

**Comment by dotcom9** [comment] 2016-02-24 11:56
I'm trying to get an ASP.NET Core (RC1) application running on an IIS virtual application in Windows 10, and I am getting the 502.3 error mentioned in this ticket. I also get the same Event Viewer messages `The description for Event ID 1000 ...`. I have tried configuring the HTTP_PLATFORM_APPL_PATH environment variable from the httpPlatformHandler configuration in web.config, but that has no effect. 

I tried deploying the application to a 2008 R2 server, with the HTTP_PLATFORM_APPL_PATH environment variable set. The application started up ok and responded as expected, but when I added a valid route to the url, the application logged `'No endpoint found for request /xxxxxxxxx.Api/api/lists/countries'`. Is there anything else that needs to be done to get this workaround to work?
![image](https://cloud.githubusercontent.com/assets/4866561/13284670/a8b434fa-daed-11e5-901b-2f9db174a7fd.png)

**Comment by Tratcher** [comment] 2016-03-08 20:05
That workaround only applies to the latest RC2 packages. For RC1 use the Map workaround instead. https://github.com/aspnet/IISIntegration/issues/14#issuecomment-171451445

**Comment by muratg** [comment] 2016-03-14 18:59
@dotcom9 Were you able to make this work in Win 2008?

**Comment by pakrym** [comment] 2018-09-07 16:43
Closing. Please reopen if new information is available or error occurs again

**Closed by pakrym** 2018-09-07 16:43 UTC
