### ISSUE TITLE
Tests fail on .NET Framework 4.6.1: IIS Express fails to start

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/IISIntegration#444] opened 2017-10-05 22:04 UTC
To repro:
`build.cmd`

**Error**
```
Failed   Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.NtlmAuthenticationTests.NtlmAuthentication_Clr_X64
Error Message:
 System.InvalidOperationException : Failed to start IIS Express
```
```
Starting IIS Express ...
Initializing the W3 Server Started CTC = 125077906
W3 Server initializing WinSock.  CTC = 125077906
W3 Server WinSock initialized.  CTC = 125077906
W3 Server ThreadPool initialized (ipm has signalled).  CTC = 125077906
Failed processing with hr = 800700c1
Error loading global modules.  hr = 800700c1
Terminating W3_SERVER object
Start listenerChannel http:0
Initializing the W3 Server Started CTC = 125079031
W3 Server initializing WinSock.  CTC = 125079046
W3 Server WinSock initialized.  CTC = 125079046
W3 Server ThreadPool initialized (ipm has signalled).  CTC = 125079046
Failed processing with hr = 800700c1
Error loading global modules.  hr = 800700c1
Terminating W3_SERVER object
InitComplete event signalled
Process Model Shutdown called
Unable to start iisexpress.
```

**OS**
Windows 10.0.16299 (Windows insiders build)
.NET Framework version: 4.7.1

Let me know if you want more logs or info to try and repro.

**Comment by jkotalik** [comment] 2017-10-05 22:51
I'm not seeing this test fail locally. @Tratcher though it is most likely an AMCM dependency, have you ever run into tests failures when running on full framework?

**Comment by Tratcher** [comment] 2017-10-09 19:31
The old tests were working fine on full framework.

**Comment by natemcmaster** [comment] 2017-11-01 21:56
This is still consistently failing for me. Have you seen this on other machines in the last month? If not, it might be bad machine state.

**Comment by jkotalik** [comment] 2017-11-01 22:49
I haven't still. I am not sure what is causing this regression. I have seen it on my machine in the past.

**Comment by ryanbrandenburg** [comment] 2017-12-01 17:50
This fails in the same way on our Win10 agent, so I think we have strong evidence for a "bad machine state" problem.

**Comment by natemcmaster** [comment] 2017-12-01 18:15
What version of Win 10 is that agent using? I wonder if this is related to the fall creator update?

**Comment by jkotalik** [comment] 2017-12-01 18:25
It is using the fall creators update, though I believe I saw this fail before locally on my machine. It's an issue with either dotnet publish or the IISExpress deployer in hosting.

**Comment by jkotalik** [comment] 2017-12-08 00:45
Issue fixed with https://github.com/aspnet/Hosting/commit/9f1e6607dd1b3d15bc6c42146629677c6b455fd0 because of net471 issues (net471 implementation of IsOS64bit is incorrect for some reason).

**Closed by jkotalik** 2017-12-08 00:45 UTC
